<?php


namespace app\widgets;


use app\models\Fight;
use Yii;
use yii\base\Widget;
use yii\data\ActiveDataProvider;

class FightWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $fight = new ActiveDataProvider([
            'query' => Fight::find()
                ->where(['status' => 2, 'first_user_id' => Yii::$app->user->id])
                ->orWhere(['status' => 2, 'second_user_id' => Yii::$app->user->id]),
            'pagination' => false,
        ]);

        return $this->render('list-view-fight',[
            'fight'=>$fight,
        ]);
    }

}