<?php


namespace app\widgets;


use app\models\UserGameRating;
use yii\base\Widget;
use Yii;
use yii\data\ActiveDataProvider;

class TopPlayersWidget extends Widget
{

    public $gamesId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if (!empty($this->gamesId)) {
            $list = new ActiveDataProvider([
                'query' => UserGameRating::find()->where(['games_id' => $this->gamesId])->orderBy('rating DESC')->limit(8),
                'pagination' => false,
            ]);
            if (empty($list)) {
                return false;
            }
            return $this->render('list-view-top-players', [
                'list' => $list,
            ]);
        }
        return false;
    }


}