<?php


namespace app\widgets;


use app\models\Tournament;
use yii\base\Widget;
use yii\data\ActiveDataProvider;

class TournamentIndexWidget extends Widget
{
    public $status;
    public $author;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->author){
            $tournament = new ActiveDataProvider([
                'query' => Tournament::find()->where(['author'=>$this->author]),
                'pagination' => false,
            ]);

            return $this->render('list-view-tournament-cabinet-index',[
                'tournament'=>$tournament,
            ]);

        }elseif ($this->status){
            $tournament = new ActiveDataProvider([
            'query' => Tournament::find()->where(['status'=>$this->status]),
            'pagination' => false,
            ]);

            return $this->render('list-view-tournament-index',[
                'tournament'=>$tournament,
            ]);
        }
        if (empty($tournament)){
            return false;
        }

    }

}