<?php


namespace app\widgets;


use app\models\Tournament;
use yii\base\Widget;
use yii\data\ActiveDataProvider;

class TournamentIndexWidget extends Widget
{
    public $status;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $tournament = new ActiveDataProvider([
            'query' => Tournament::find()->where(['status'=>$this->status]),
            'pagination' => false,
        ]);
        if (empty($tournament)){
            return false;
        }
        return $this->render('list-view-tournament-index',[
            'tournament'=>$tournament,
        ]);
    }

}