<?php


namespace app\widgets;


use app\models\User;
use yii\base\Widget;
use yii\data\ActiveDataProvider;

class UserLayoutWidget extends Widget
{
    public $userId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $user = new ActiveDataProvider([
            'query' => User::find()->where(['id'=>$this->userId]),
            'pagination' => false,
        ]);

        if (empty($user)){
            return false;
        }
        return $this->render('list-view-user-layout',[
            'user'=>$user,
        ]);
    }
}