<?php


namespace app\widgets;


use app\models\TournamentToUser;
use app\models\User;
use yii\base\Widget;
use yii\data\ActiveDataProvider;

class UserTournamentWidget extends Widget
{

    public $tournamentId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $user = new ActiveDataProvider([
            'query' => TournamentToUser::find()->where(['tournament_id'=>$this->tournamentId]),
            'pagination' => false,
        ]);

        if (empty($user)){
            return false;
        }
        return $this->render('list-view-user-tournament',[
            'user'=>$user,
        ]);
    }

}